apiVersion: apps/v1
kind: Deployment
metadata:
  name: myresume-demo
  namespace: test
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: footstepsolutions/myresume:v1
        ports:
        - containerPort: 80
