kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: frontend-service
  namespace: test
spec:
  rules:
  -
    host: color.cloudgypsy.com.au
    http:
      paths:
      -
        path: /
        backend:
          serviceName: frontend-service
          servicePort: 80
