apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: frontend-service
  namespace: test
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 80
    nodePort: 30031
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}
